# Generated by Django 4.2 on 2023-12-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_item_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('percent_dis', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'United States dollar')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment_app.discount'),
            preserve_default=False,
        ),
    ]
